### ISSUE TITLE
vendor/bower/sweetalert/docs-src/assets/sweetalert): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by Cuihongsen** [yii2mod/yii2-sweet-alert#8]
opendir(/Users/cui/code/dev_test/vendor/bower/sweetalert/docs-src/assets/sweetalert): failed to open dir: No such file or directory
我看了一下，vendor/bower/sweetalert/docs-src/assets/sweetalert 是一个无效链接

**Comment by Cuihongsen** [comment]
sweetalert -> ../../dist/  vendor/bower/sweetalert/dist The directory does not exist

**Comment by ihorchepurnyi** [comment]
I'll fix this issue

**Comment by Cuihongsen** [comment]
I found the reason
sweetalert update to v2
I add  "bower-asset/sweetalert": "v1.1.3" into my composer.json
now is OK

**Comment by ihorchepurnyi** [comment]
Ok, I updated composer.json
