### ISSUE TITLE
Missing sweetalert.min.js

### ISSUE THREAD

**Issue by Sensetivity** [yii2mod/yii2-sweet-alert#9]
![image](https://user-images.githubusercontent.com/4289543/30418130-a05219d2-993a-11e7-91dd-6ee132c329fc.png)

I think it because you replace bower to npm but not change alias in Asset class.

**Comment by ihorchepurnyi** [comment]
Hi, can you install `dev-master` version of this package and check it again

**Comment by launcherx** [comment]
Hi. I see You fixed dependency with "bower-asset/sweetalert" : "1.1.3", but You forgot to make release with new tag and update packagist entry. Please do it ASAP. I'm not using "dev-master", but  "~1.2" so i can't get fixes.

**Comment by MaksimKiselev** [comment]
+1

**Comment by ihorchepurnyi** [comment]
I made the new release v 1.3.

**Comment by MaksimKiselev** [comment]
@igor-chepurnoi thank you!

**Comment by Sensetivity** [comment]
@igor-chepurnoi Thanks
